#Start code here
from turtle import *
screen = Screen()
turtle = Turtle()
screen.bgcolor(0, 1, 0)
turtle.speed(10)
turtle.width(10)
turtle.pencolor(255, 215, 1)
turtle.goto(10, -25)
turtle.fillcolor(255, 215, 1)
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.goto(30, 90)
turtle.color(0, 0, 0)
turtle.pendown()
turtle.circle(8)
turtle.penup()
turtle.goto(-15, 90)
turtle.pendown()
turtle.color(0, 0, 0)
turtle.circle(8)
turtle.penup()
turtle.goto(-40, 40)
turtle.pendown()
turtle.setheading(-90)
turtle.width(5)
turtle.circle(50,180)
#Additionally, play with different rgb colors from- https://flaviocopes.com/rgb-color-codes/ # your own code
